language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.1.5
  - 2.2.1
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get update
  - sudo apt-get install libgdal-dev
